export const skills = [
  {
    name: "JavaScript",
    level: 80,
    image: "JS.png",
  },
  {
    name: "TypeScript",
    level: 60,
    image: "TS.png",
  },
  {
    name: "React.js",
    level: 90,
    image: "react.png",
  },
  {
    name: "Next.JS",
    level: 90,
    image: "next1.png",
  },
  {
    name: "React Native",
    level: 70,
    image: "react.png",
  },
  {
    name: "Vue.JS",
    level: 70,
    image: "vue.png",
  },
  {
    name: "Nuxt.JS",
    level: 60,
    image: "nuxt.png",
  },
  {
    name: "Node.js",
    level: 80,
    image: "node.png",
  },
  {
    name: "Strapi.JS",
    level: 90,
    image: "strapi.png",
  },
  {
    name: "Postgresql",
    level: 70,
    image: "postgres.png",
  },
  {
    name: "MongoDB",
    level: 70,
    image: "mongo.png",
  },
  {
    name: "MySQL",
    level: 60,
    image: "mysql.png",
  },
  {
    name: "Puppeteer",
    level: 80,
    image: "pupp.png",
  },
  {
    name: "Playwright",
    level: 60,
    image: "playwright.png",
  },

  {
    name: "Docker",
    level: 50,
    image: "docker.png",
  },
  {
    name: "Heroku",
    level: 70,
    image: "heroku.png",
  },

  {
    name: "Plesk",
    level: 80,
    image: "plesk.png",
  },
  {
    name: "GIT",
    level: 80,
    image: "git.png",
  },
  {
    name: "GITLAB",
    level: 80,
    image: "gitlab.png",
  },
  {
    name: "Bitbucket",
    level: 60,
    image: "bitbucket.png",
  },
];

export const projects = [
  {
    name: "Planet of finance",
    link: "https://planetoffinance.com/",
    withLink: true,
    logo: "pof.png",
    bg: "pof.jpg",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Social Media",
    device: "Desktop/Mobile - Mobile Application",
    height: "500",
    width: "700",
    platform: ["pc", "mobile", "android", "apple"],
    color: "#FF7F50",
    date: "Mar 2023",
  },
  {
    name: "Moneeverse",
    link: "https://moneeverse.com/",
    withLink: true,
    logo: "moneeverse.png",
    bg: "moneeverse.png",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Social Media / Metaverse",
    device: "Desktop/Mobile",
    height: "500",
    width: "600",
    platform: ["pc", "mobile"],
    color: "#6495ED",
    date: "Jan 2023",
  },
  {
    name: "Poseidon Spa",
    link: "https://www.poseidon-spa.com/",
    withLink: true,
    logo: "poseidon.png",
    bg: "poseidon.jpg",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Website",
    device: "Desktop/Mobile",
    height: "500",
    width: "500",
    platform: ["pc", "mobile"],
    color: "#FFD700",
    date: "Jul 2022",
    type: "Social media",
  },
  {
    name: "Monaco Water Games",
    link: "https://monacowatergames.mc/",
    withLink: true,
    logo: "mwg.png",
    bg: "mwg.jpg",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Website",
    device: "Desktop/Mobile",
    height: "500",
    width: "600",
    platform: ["pc", "mobile"],
    color: "#8FBC8F",
    date: "Jun 2023",
  },
  {
    name: "Agilix",
    // link: "https://www.poseidon-spa.com/",
    withLink: false,
    logo: "poseidon.png",
    bg: "agilix.jpg",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Web Application",
    device: "Desktop",
    height: "500",
    width: "600",
    platform: ["pc", "mobile"],
    color: "#FF69B4",
    date: "Jul 2022",
  },
  {
    name: "Dashboard",
    // link: "https://www.poseidon-spa.com/",
    withLink: false,
    logo: "poseidon.png",
    bg: "admin.png",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Web Application",
    device: "Desktop",
    height: "600",
    width: "600",
    platform: ["pc", "mobile"],
    color: "#3CB371",
    date: "Jul 2022",
  },
  {
    name: "Ma Pergola",
    link: "https://ma-pergola.fr/",
    withLink: true,
    logo: "pergola.png",
    bg: "pergola1.jpg",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Web Application",
    device: "Desktop/Mobile",
    height: "500",
    width: "600",
    platform: ["pc", "mobile"],
    color: "#FFA500",
    date: "Mar 2021",
  },
  {
    name: "Tendances Group",
    link: "https://tendances.group/",
    withLink: true,
    logo: "TG.png",
    bg: "TG.png",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Website",
    device: "Desktop/Mobile",
    height: "500",
    width: "700",
    platform: ["pc", "mobile"],
    color: "#9370DB",
    date: "Jan 2023",
  },
  {
    name: "Tendances Dev",
    link: "https://tendances.dev/",
    withLink: true,
    logo: "TD.png",
    bg: "TD.png",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Website",
    device: "Desktop/Mobile",
    height: "500",
    width: "500",
    platform: ["pc", "mobile"],
    color: "#32CD32",
    date: "Feb 2023",
  },
  {
    name: "Tendances Top",
    link: "https://tendances.top/",
    withLink: true,
    logo: "TT.png",
    bg: "TT1.jpg",
    society: "Tendances Group",
    societyLink: "https://tendances.group",
    type: "Website",
    device: "Desktop/Mobile",
    height: "500",
    width: "700",

    platform: ["pc", "mobile"],

    color: "#FFC0CB",
    date: "Dec 2022",
  },
  {
    name: "Cybeletech",
    link: "https://www.cybeletech.com/",
    withLink: true,
    logo: "TT.png",
    bg: "cybel.jpg",
    // society: "Digital Expert",
    // societyLink: "https://tendances.group",
    type: "Web Application",
    device: "Desktop/Mobile",
    height: "500",
    width: "600",
    platform: ["pc", "mobile", "apple", "android"],
    color: "#40E0D0",
    date: "Jul 2021",
  },
  {
    name: "Sésame",
    withLink: true,
    logo: "TT.png",
    bg: "sesame.png",
    // society: "Digital Expert",
    // societyLink: "https://tendances.group",
    type: "Web Application",
    device: "Desktop/Mobile",
    height: "500",
    width: "600",
    platform: ["pc", "mobile"],
    color: "#FF4500",
    date: "Jul 2021",
  },
  {
    name: "Eduq",
    link: "https://www.eduq.fr/",
    withLink: true,
    logo: "TT.png",
    bg: "eduq.jpg",
    // society: "Digital Expert",
    // societyLink: "https://tendances.group",
    type: "Website",
    device: "Desktop/Mobile",
    height: "500",
    width: "600",
    platform: ["pc", "mobile"],
    color: "#6A5ACD",
    date: "Mar 2020",
  },
];
